---
title: "Predicting and Understanding NBA Career Length"
author: "Brandon Chan + Lucas Duncan"
date: "2025-03-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(e1071)
library(MASS)
library(tidyverse)
library(caret)
library(leaps)
library(tidyr)
library(ggplot2)

select <- dplyr::select
```

## Executive Summary and Contents

```{r}
contents <- tribble(
  ~Index, ~Category, ~Method,
  1, "Introduction", "Written",
  2, "Preprocessing", "Data Description and Encoding",
  3, "Unsupervised Learning/Analysis", "PCA and Clustering",
  4, "Preprocessing", "Variable Selection",
  5, "Supervised Regression", "Linear and Non-Linear Regression",
  6, "Supervised Classification", "LDA/QDA and Logistic Regression",
  7, "Supervised Classification", "Tree-Based Methods",
  8, "Supervised Classification", "Support Vector Machines",
  9, "Deep Learning", "Neural Networks",
  10, "Conclusion", "Written", 
)
contents

```


### 2: Preprocessing

#2.1 Extract Data
```{r, warning=FALSE}

location = "https://raw.githubusercontent.com/BrandonYChan/Statistical-Learning/main/Student_performance_10k.csv"

df <- read_csv(location, show_col_types = FALSE) 

#NOTE: GPA IS AVERAGE OF 4 courses, FOR MODEL THUS CANT USE ALL 4 AT ONCE

df
```

#2.2 Clean Data
```{r}

df2 <- df |>
  
       rename(
         "has_subsidized_lunch" = "lunch",
         "has_prepared" = "test_preparation_course",
         "is_male" = "gender",
         "parent_education" = "parental_level_of_education",
         "gpa" = "grade"
       ) |> 
       mutate(
         is_male = as.integer(if_else(is_male =="male",1,0)),
         race_ethnicity = str_sub(df$race_ethnicity, -1, -1),
         gpa = gpa/4
       ) |>
       select(-c("roll_no",
                 "science_score",
                 "writing_score"    #REMOVE FOR NOW!!!!!!!!!!!!!!!!!!!!!!!!!
                 ))
```


#2.3 Interpolate NA values
```{r}

#Remove Any Duplicates
df3 <- distinct(df2)

#Replace Missing NUMERIC (Including Date) Values With ColMean
if (any(is.na(df3))) {
  df3[] <- lapply(df3, function(x) {
    if (is.numeric(x)) {
      replace(x, is.na(x), mean(x, na.rm = TRUE))
    } else {
      x
    }
  })
}

#Dropping Missing Factor Columns
df3 <- df3[complete.cases(df3[c("race_ethnicity", "parent_education")]), ]
```

#2.4 Format For Classification + Regression
```{r}

#For Regression We Convert All Categories Into ONEHOT Notation
df_reg <- df3 |> 
          bind_cols(as.data.frame(model.matrix(~ `race_ethnicity` + `parent_education` - 1, data = df3))) |>
          select(-c("race_ethnicity","parent_education"))

df_cls <- df3 |> 
          mutate(
            race_ethnicity = as.factor(race_ethnicity),
            parent_education = as.factor(parent_education)
          )
```


#2.5 Display Variable Distributions
```{r}

df_numeric <- df_cls |>
              select(where(is.numeric)) |>
              pivot_longer(cols = everything(), names_to = "variable", values_to = "value")

ggplot(df_numeric, aes(x = value)) +
geom_histogram(bins = 30) +  
facet_wrap(~ variable, scales = "free") +
labs(title = "Numeric Distributions", x = "Value", y = "Frequency") 


df_factor <- df_cls |>
             select(where(is.factor)) |>
             pivot_longer(cols = everything(), names_to = "variable", values_to = "value") 

ggplot(df_factor, aes(x = value)) +
geom_bar() +  
facet_wrap(~ variable, scales = "free") +  
labs(title = "Factor Distributions", x = "Value", y = "Frequency")

```
#2.6 Split Into Train + Test Sets
```{r}

train_index <- which(runif(nrow(df2)) < 0.8)

train_reg <- df_reg[train_index,]
test_reg <- df_reg[-train_index,]

train_cls <- df_cls[train_index,]
test_cls <- df_cls[-train_index,]


```






# 2 Data Exploration with Unsupervised Methods 


##2.1 Principal Component Analysis

```{r}

# Find Principal Components
pr <- prcomp(df_reg, scale=TRUE)

# Show Impact of Variables on the First Principle Component
pc1 <- pr$rotation[,1]
(pc1_loading_df <- cbind(names(pc1), as_data_frame(pc1)) |>
                  rename("names" = "names(pc1)", "pc1_loading" = "value") |> 
                  arrange(desc(abs(pc1_loading))))

```


```{r}
# Show Proportion of Variance Explained (PVE)
pve <- pr$sdev^2 / sum(pr$sdev^2)   

pve_df <- as_data_frame(cbind(1:length(pve), pve)) %>% # Show PVE for each number of principal components
  mutate(cumulative_pve = cumsum(pve)) %>% # Cumulative PVE for each additional PC 
  rename("num_principal_components" = "V1")
  
pve_df
```


```{r}
# Show projections of data onto first 2 PCs
biplot(pr, scale = 0, cex=0.4)
```

## K-Means Clustering on PC1 and PC2

```{r}
km <- kmeans(pr$x, 3, nstart=20)
plot(pr$x, col = (km$cluster +1), pch=20, cex=2)
```






